### PR TITLE
Overhaul Modules - implement nicer command

### PR DESCRIPTION
**Pull request by TheRealRyGuy**
__Changes so Far__
* Implement an `@ModuleInfo` annotation onto each Module, supplying description for eventual tooltips / nice tab competition of commands 
* All module implementations were refactored to `org.purpurmc.purpurextras.modules.impl`
* `ModuleManager` now stores and handles all live Module manipulation and storage
* `AnvilSplitsMinecartsAndBoatsModule` was split into a Minecarts and a Boats module 
* `ShieldSettingsModule` module was split into `ShieldDamageReductionModule` and `ShieldCooldownModule`
* `OpenIronDoorsModule` was split into `OpenIronDoorsWithHand` and `OpenIronTrapdoorsWithHand`
* Fixes smithing modules in the interim before they become data packs by just not requiring a template 
* `PurpurExtrasModule` is now abstract class with the following changes 
  * inherits `Listener`
  * Now the only required method is `String getConfigPath()`, which will handle all registration logic
  * Given default logic, essentially allowing the only required things to implement being event handlers and `#getConfigPath`
  * Given config getters to reduce boilerplate, with the end goal of not needing `PurpurExtras#getPurpurConfig` calls outside of `PurpurExtrasModule` or even just not needing it and passing it as an instance
* Implements a test to ensure all Modules are valid (they have a proper annotation) 
  * This opens up the potential for module unit tests using [MockBukkit](https://github.com/MockBukkit/MockBukkit)
    * Needs to wait for [this pr](https://github.com/MockBukkit/MockBukkit/pull/792), probably will just put this into another PR
* All Modules had the word `Module` removed from the class name 
* [CommandAPI](https://github.com/JorelAli/CommandAPI) now handles all command work
* Moved entire `gameplay-settings` config section to just `settings.[module]` - this should naturally port by itself

__Module Port Progress__ 

- [x] AnvilChangesBlocksModule
- [x] AnvilSplitsBoatsModule
- [x] AnvilSplitsMinecartsModule
- [x] BeeHiveLoreModule
- [x] CancelPetDamageFromOwnerModule
- [x] ChorusFlowerAlwaysDropsModule
- [x] ColoredBossBarModule
- [x] CreateSusBlocksModule
- [x] DispenserBlocksModule
- [x] EscapeCommandSlashModule
- [x] ForceNametaggedForRidingModule
- [x] FurnaceBurnTimeModule
- [x] GrindstoneEnchantsBooksModule
- [x] InvisibleItemFrameModule
- [x] LightningTransformsMobsModule
- [x] LootBlocksProtectionModule
- [x] MobNoTargetModule
- [x] NetherBuildHeightModule
- [x] NoFallDamageWhil,eHavingJumpBoostModule
- [x] OpenIronDoorsWithHandModule
- [x] OpenIronTrapdoorsWithHandModule
- [x] RespawnAnchorNeedsChargeModule
- [x] RunFasterOnPathsModule
- [x] ShieldCooldownModule
- [x] ShieldDamageReductionModule
- [x] SleepPercentageMessageModule
- [x] SpawnerPlacementPermissionsModule
- [x] StonecutterDamageModule
- [x] UnlockAllRecipesModule
- [x] UpgradeIronToDiamondsToolsModule
- [x] UpgradeStoneToIronToolsModule
- [x] UpgradeWoodToStoneToolsModule
- [x] VoidTotemModule

### CODE REVIEW

**Comment by YouHaveTrouble** [comment]
Woah, that's a lot of text!

With making PurpurExtrasModule an abstract class, I think it's not really necessary at this point, but I'm open to discussion about this.

I don't think mockbukkit is a good idea here, as afaik it does not offer support for purpur api that will likely be used in future modules.

Settings under gameplay-settings and similar subcategories date back to the very beginning of the plugin, I'm fine with them breaking, although config version could be introduced and a migration system can be created to safely move the options to the new config format without breaking the behavior. The ideal scenario to not split the config into sections like that since it just ended up with confusion to where things should be added. The only separate logic is for the shield features iirc and we can also have a discussion about that too, because situations where we won't always want to register all listeners in the module will occur sooner or later.

The entire dispenser module should probably be rewritten, but I don't really have an idea how to handle that logic in a nicer way at this point.

Ping me on discord at any time to talk about this, whenever you have time

**Comment by TheRealRyGuy** [comment]
- All modules are now done except for Dispenser module - this included splitting up shield and iron doors modules into multiple things 
- PurpurExtrasModule is now an abstract class with a `#isEnabled` method - not sure how far we want to go containerizing the plugin / config file. 
  - Should we pass `PurpurConfig` or `PurpurExtras` per module? Do we want to use strictly DI on PurpurExtras? 
- Gameplay settings (should?) be migrated nicely into their own `settings.[module]` config path 
- Mitigated config utils nicely to allow for schema changes - all modules just depend on their getConfigPath, and the custom config getters used per module depend on that 

need to test backwards compat at some point to see if it actually does nicely migrate,  but is probably ready for a proper review of the module system

**Comment by TheRealRyGuy** [comment]
[CommandAPI](https://github.com/JorelAli/CommandAPI) is now implemented for all current commands 
__Next Steps__
- Needs a review from someone that isn't me blindly doing things 
- Need to think about config schema and test current backwards compat of config 
- Need to figure out what to do with Dispenser module 
- Need to figure out what commands are currently wanted. My list: 
  - `/purpurextras modules` - shows currently enabled modules 
  - `/purpurextras enable [module]` and `/purpurextras disable [module]` 
 
and this all needs testing :D but i think i'm done (hopefully) for now

**Review by YouHaveTrouble — COMMENTED** [review]
So far so good, only thing I don't like is abbreviations in package names, `cmd` isntead of `commands` and `impt` instead of `implementation`.
Try not to abbreviate names like that since names of packages, methods, classes etc. should be self describing

**Comment by TheRealRyGuy** [comment]
removed abbreviations too 👍

**Comment by TheRealRyGuy** [comment]
- Deleted tool modules 
- Hard enabled Dispensers module with old logic 
- Added message to console whenever a module is enabled 
i should probably open an issue to track bugs for this, but unmarking as a draft because it looks ready to test?

**Comment by TheRealRyGuy** [comment]
made use of caching in the same way purpur does

**Comment by TheRealRyGuy** [comment]
pulled over creepersquids

**Comment by YouHaveTrouble** [comment]
I am closing this due to inactivity. Parts of this will be implemented separately.

**Pull request closed without merging**
